[tool.poetry]
name = "lp-or-tools"
version = "0.1.0"
description = ""
authors = ["Guilherme Prado <guizmk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ortools = "^9.9.3963"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
